### ISSUE TITLE
use of "open" in run.sh leads to "Couldn't get a file descriptor referring to the console"

### ISSUE THREAD

**Issue by BenedictWilkins** [dicelab-rhul/web-agent#112]
there seems to be a problem with this line in `run.sh`
```
sleep 2 && open ${PROTOCOL}://${HOST}:${PORT} &
```

**Comment by BenedictWilkins** [comment]
on mac open will open the browser but this doesn't work on linux...? perhaps bin/open? otherwise we will need to locate the default browser?

**Comment by cloudstrife9999** [comment]
#115 improves upon 196841bff1c3743f558f72a5f6b77946541bb0ba by not aborting in case no suitable browser opener is found. Rather, the user is asked to open the URL manually.
